// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Auth struct {
	User  *User  `json:"user"`
	Token string `json:"token"`
}

type User struct {
	Name        string `json:"name"`
	Username    string `json:"username"`
	Email       string `json:"email"`
	Avatar      string `json:"avatar"`
	AccountType int    `json:"accountType"`
}
